# Generated by Django 5.1.7 on 2025-04-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('company', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2023)),
                ('color', models.CharField(default='black', max_length=50)),
                ('seats', models.IntegerField(default=5)),
                ('luggage_capacity', models.IntegerField(default=2)),
                ('fuel_type', models.CharField(default='petrol', max_length=50)),
                ('transmission', models.CharField(default='automatic', max_length=50)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('gps', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('child_seat', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('parking_sensors', models.BooleanField(default=False)),
                ('heated_seats', models.BooleanField(default=False)),
                ('sunroof', models.BooleanField(default=False)),
                ('navigation_system', models.BooleanField(default=False)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
